### ISSUE TITLE
when request is present, cache is disabled

### ISSUE THREAD

**Issue by schwannden** [long2ice/fastapi-cache#107]
Due to this line:
https://github.com/long2ice/fastapi-cache/blob/8f0920d0d7f0a34bfb8987736cf794be5e3cc33f/fastapi_cache/decorator.py#L128

When request is present, cache is disabled. Why do we do so? Isn't it quite normal if user want to customize key builder that takes in request object?

I can create a pr to fix this but just wondering why the design is so in the first place.

**Comment by mkdir700** [comment]
because `@cache` can be apply for general function or method, like this:

<img width="818" alt="image" src="https://user-images.githubusercontent.com/56359329/210907507-5abb96e3-e6e6-4a20-8eae-a17e371f5f0e.png">

when request is present, it will run there

https://github.com/long2ice/fastapi-cache/blob/8f0920d0d7f0a34bfb8987736cf794be5e3cc33f/fastapi_cache/decorator.py#L151

**Comment by mjpieters** [comment]
Pretty sure this was never an issue, but perhaps the refactoring work done in #139 makes it easier to understand when caching is applied and when not.
