### ISSUE TITLE
cache is not working

### ISSUE THREAD

**Issue by nagarjuna06** [long2ice/fastapi-cache#446]
I've tried implementing the fastapi-cache2 package, but I'm consistently getting a MISS value for the cache header. I've verified my configuration and Redis connection settings.

Could you please help me identify the issue or provide guidance on troubleshooting?
![image](https://github.com/user-attachments/assets/1a492619-1a42-4c8c-85e3-2bf37c087d03)

**Comment by rseeley** [comment]
I'm having this issue, as well, using Redis as the backend on an async function.

Edit: I'm seeing the same issue when using `InMemoryBackend`.

**Comment by vicchi** [comment]
@nagarjuna06 @rseeley See #447 for an example of a working and verified "quick start". If you can post your environment, versions and a reproducible test case that would help massively.

**Comment by MJimmyChen-reform** [comment]
@nagarjuna06 @rseeley I assume you are trying this solely through the Swagger UI and haven't tried looking into Redis Insight with caching it via directly calling the endpoint or through Postman?
Because I found out that Swagger UI is somehow always returning MISS (check my latest post in https://github.com/long2ice/fastapi-cache/issues/442) but haven't found the exact thing causing this.
